### PR TITLE
Add name and icon for PWA

### PR DESCRIPTION
**Pull request by thomasbnt**
Maybe also add PWA icon ? How we can add that?

image

### CODE REVIEW

**Comment by thomasbnt** [comment]
Actual changes with the preview deploy : 

image

**Comment by T-Zahil** [comment]
Hey, thank you for your PR 🙏. I always forget about PWA settings!

Normally the icon should have worked normally according to Nuxt documentation (https://pwa.nuxtjs.org/icon), but it seems not ahah. I added a little config line to make it work!

**Comment by thomasbnt** [comment]
Hey! The icon does not appear :c 
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 96.0.4664.110 on Windows 10
Viewport:  1920 x 937 @1x
Language:  fr
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-10--naughty-kare-906acd.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=96.0&resolution=1920x937&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-10--naughty-kare-906acd.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61d8a71de938990007aa3916&commentID=61d8a81e9d115d3561790eb3&resolution=resolved)

**Comment by T-Zahil** [comment]
Yeah same for me, but it works on local... Strange 🤔

**Comment by thomasbnt** [comment]
Maybe it's the cache 😵

**Comment by T-Zahil** [comment]
Yeah it works 🥳  it was the cache!

**Comment by thomasbnt** [comment]
Youhouuu !

**Pull request merged**
