### PR TITLE
fixed some mistakes

### PR DESCRIPTION
**Pull request by mlaarebi**
It would be great if you could add RTL support. Many languages needs it.

### CODE REVIEW

**Comment by T-Zahil** [comment]
You're right! I add it to my todo-list, I'm sure I18N support it :)

**Comment by mlaarebi** [comment]
for the vocabulary, I kept the English word and added the Arabic meaning, do you prefer if I add the Arabic translation too, before the explanation?

**Comment by T-Zahil** [comment]
I saw! Well in French I've let the English words as some of them don't translate well 😄 so you can do the same I think!

**Comment by mlaarebi** [comment]
I'll add them, that would add value to the reader.

**Pull request merged**
